"""
GenerateREADME — Auto-generates README files for the LSTM model.
=================================================================
Three READMEs are produced:
  - README_Training.md   → written at the end of training (LSTMTraining.py)
  - README_Evaluation.md → written after all evaluation plots are saved (Plotting.py)
  - README_Ensemble.md   → written after ensemble plots are saved (EnsembleOutput.py)

All are saved to the run's plot/output directory.
"""

import os
from datetime import datetime


# ============================================================
# Training README
# ============================================================

def generate_training_readme(plot_dir, model_filename, config,
                              train_size, val_size, test_size, n_total,
                              epochs_run, best_epoch, best_val_loss,
                              early_stopped, patience):
    """
    Write README_Training.md to plot_dir immediately after training completes.

    Args:
        plot_dir       : Directory where the README is saved.
        model_filename : Filename of the saved checkpoint (e.g. model_v3.pth).
        config         : The Config instance used for training.
        train_size     : Number of training samples.
        val_size       : Number of validation samples.
        test_size      : Number of test samples.
        n_total        : Total dataset size.
        epochs_run     : Total number of epochs that were executed.
        best_epoch     : Epoch at which the best validation loss was recorded.
        best_val_loss  : Best validation loss (GaussianNLLLoss).
        early_stopped  : True if training was stopped early by the patience mechanism.
        patience       : The early-stopping patience value that was configured.
    """
    train_pct = train_size / n_total * 100
    val_pct   = val_size   / n_total * 100
    test_pct  = test_size  / n_total * 100
    stop_note = (f"Yes — no improvement for {patience} consecutive epochs "
                 f"(stopped at epoch {epochs_run})")  if early_stopped else "No — ran to completion"
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Collect all scalar config attributes (handles class- and instance-level attrs)
    config_rows = ""
    for key in sorted(dir(config)):
        if key.startswith("_"):
            continue
        value = getattr(config, key)
        if callable(value):
            continue
        config_rows += f"| `{key}` | {value} |\n"

    content = f"""\
# LSTM Training Run — Summary

Auto-generated by `LSTMTraining.py` on {generated_at}.

---

## Model

| Property | Value |
|---|---|
| Checkpoint file | `{model_filename}` |
| Best checkpoint epoch | {best_epoch} |
| Best validation loss (GaussianNLL) | {best_val_loss:.6f} |
| Total epochs run | {epochs_run} |
| Early stopping triggered | {stop_note} |

---

## Dataset Split

| Split | Samples | Percentage |
|---|---|---|
| Train | {train_size} | {train_pct:.1f}% |
| Validation | {val_size} | {val_pct:.1f}% |
| Test | {test_size} | {test_pct:.1f}% |
| **Total** | **{n_total}** | **100%** |

The split is **chronological** — no data leakage. The test set is always the most
recent {test_pct:.1f}% of the data and is never touched during training.

---

## Hyperparameters (Config)

| Parameter | Value |
|---|---|
{config_rows}\
---

## Loss Curve

![Train vs Validation Loss](Plots/train_val_loss.png)

The training and validation loss curve is generated automatically alongside this README.

### How to interpret it

| Pattern | Meaning |
|---|---|
| Both curves decrease together | Training is progressing correctly |
| Val loss plateaus while train loss keeps falling | Overfitting — consider more dropout or less capacity |
| Both curves are flat from the start | Learning rate too low, or gradient issue |
| Loss spikes during training | Gradient explosion — check grad clipping |
| Best epoch is very early | Early stopping may have fired too soon — consider raising patience |
| Best epoch is near the configured max | Model may still improve with more epochs |

---

## Notes

- Loss function: **GaussianNLLLoss** — the model outputs a mean (`mu`) and
  log-variance (`log_var`) for each forecast step. The loss rewards both
  accurate point predictions and well-calibrated uncertainty estimates.
- Gradient clipping is applied at `max_norm = 1.0` per step to prevent
  exploding gradients in the 168-step sequence.
- The learning rate scheduler (`ReduceLROnPlateau`, factor=0.5, patience=3)
  halves the learning rate whenever validation loss stops improving.
"""
    readme_path = os.path.join(plot_dir, "README_Training.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)


# ============================================================
# Evaluation README
# ============================================================

def generate_evaluation_readme(plot_dir, best_epoch, best_val_loss,
                                n_test_samples, train_size, val_size, test_size, n_total,
                                model_filename="unknown"):
    """
    Write README_Evaluation.md to plot_dir explaining every evaluation plot,
    every panel, and how to interpret patterns in them.
    """
    train_pct = train_size / n_total * 100
    val_pct   = val_size   / n_total * 100
    test_pct  = test_size  / n_total * 100

    content = f"""\
# LSTM Forecast — Evaluation Plots

Auto-generated by `Plotting.py`.

## Model & Dataset Summary

| Property | Value |
|---|---|
| Model file | `{model_filename}` |
| Best checkpoint epoch | {best_epoch} |
| Best validation loss (GaussianNLL) | {best_val_loss:.6f} |
| Total samples | {n_total} |
| Train split | {train_size} ({train_pct:.1f}%) |
| Validation split | {val_size} ({val_pct:.1f}%) |
| Test split | {test_size} ({test_pct:.1f}%) |
| Forecast horizon | 168 hours (7 days) |
| Encoder history | 168 hours (7 days) |

---

## Plots Overview

| File | Contents |
|---|---|
| `test_predictions.png` | Three representative 168-hour forecast windows |
| `actual_vs_predicted.png` | Actual vs predicted scatter at 1h, 24h, and 168h ahead |
| `residuals.png` | Residual diagnostics: error over time, quantile heatmap, variance ratio |
| `per_horizon_metrics.png` | Per-horizon MSE / RMSE / MAE / MAPE / R² vs persistence baseline |

---


## Example Forecast Windows

![Example Forecast Windows](test_predictions.png)

### What it shows
Three 168-hour forecast windows sampled evenly from the test set (early, middle, late).
Each panel shows the actual abvaerk (blue) and the model prediction (red) over the full
7-day horizon. The MAE and date range for that window are shown in the title.

### How to interpret

| Pattern | Meaning |
|---|---|
| Red line tracks blue closely | Model is working well for that period |
| Red line is flat / near-constant | Model is predicting the mean — under-trained or mean-regressing |
| Red line tracks the shape but is shifted up or down | Systematic bias for that period |
| Errors are larger in one window than another | Model performs differently across seasons or weather regimes |
| Red line overshoots peaks | Model is over-dispersed for that window |

The three windows are spaced across the full test set so you can compare performance
across different time periods (e.g. early autumn vs late winter).

---

## Actual vs Predicted at Three Horizons

![Actual vs Predicted](actual_vs_predicted.png)

### What it shows
Three scatter plots side by side, each showing actual abvaerk (x-axis) against the
model's predicted abvaerk (y-axis) for a specific forecast horizon step. Each point
represents one test window. The dashed diagonal is the identity line `y = x` (perfect
prediction). The R² score for that horizon is shown in the title.

| Panel | Horizon | Description |
|---|---|---|
| Left | h=0 (1h ahead) | Sharpest prediction — model has the most context |
| Middle | h=23 (24h ahead) | 1-day-ahead prediction |
| Right | h=167 (168h ahead) | 7-day-ahead prediction — hardest step |

A small random jitter is added to the x-axis to separate overlapping points and reveal
density structure that would otherwise be hidden.

### How to interpret

| Pattern | Meaning |
|---|---|
| Points clustered tightly on the diagonal | High accuracy at that horizon |
| Scatter grows from left to middle to right panel | Normal degradation — model gets less accurate further out |
| Points form a fan shape (wider at high actual values) | Heteroscedastic error — model struggles more at peak demand |
| Points systematically above the diagonal | Model over-predicts on average at that horizon |
| Points systematically below the diagonal | Model under-predicts on average at that horizon |
| Middle and right panels look similar to the left | Model is not degrading with horizon — strong weather forecast features or mean regression |
| Two distinct clusters of points | Possible bi-modal demand (e.g. heating season vs non-heating) |
| R² drops sharply from left to right | Expected — forecast accuracy degrades with horizon distance |
| R² stays similar across all three panels | Either genuinely good long-range skill, or mean regression (check variance ratio plot) |

---

## Residual Diagnostics

![Residual Diagnostics](residuals.png)

### Panel layout
```
┌──────────────────────────────────────┐
│  Panel A: MAE over time (full width) │
├──────────────────────┬───────────────┤
│  Panel B: Quantile   │  Panel C:     │
│  error heatmap       │  Variance     │
│                      │  ratio        │
└──────────────────────┴───────────────┘
```

### Panel A — Forecast Error Over Time
MAE for each test window plotted in chronological order (one point = one 168-hour forecast
starting at that date). A red rolling mean (168-sample window) is overlaid to show the
trend.

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Gradual upward trend over time | Model degrades on later data — possible distribution shift |
| Sharp spike at a specific date | Model failed on an unusual event (cold snap, heat wave, holiday) |
| Lower error in summer, higher in winter | Model handles low-demand periods well but struggles with heating season |
| Error decreases over time | Test set may start mid-season transition and stabilise |
| Flat, consistent error throughout | Model generalises well across all periods |

The November transition spike (if present) is a classic heating season onset pattern for
district heating — sudden demand increases that the model has not seen enough of in training.

### Panel B — Absolute Error Distribution by Horizon (quantile heatmap)
A 2D heatmap where:
- **X-axis**: forecast horizon in hours (1 = 1h ahead, 168 = 7 days ahead)
- **Y-axis**: error percentile (p5 = best 5% of windows, p95 = worst 5%)
- **Colour**: absolute error in MWh (yellow = low, dark red = high)

Vertical white dashed lines mark day boundaries (1d, 2d, … 7d).

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Colour gets darker left to right | Error grows with horizon — normal degradation |
| Colour is uniform across the full x-axis | Error does not grow with horizon — either genuinely good (weather forecasts help) or mean-regression (model predicts average regardless of horizon) |
| Only the top rows (p90, p95) darken at long horizons | Tail errors grow faster than median — worst-case scenarios are harder to predict far out |
| All rows darken uniformly | Error distribution shifts up uniformly with horizon |
| Dark colours near the top even at short horizons | Large worst-case errors even at 1–2h ahead — high-variance regime |

A flat heatmap that is uniformly coloured across the x-axis is ambiguous on its own.
Cross-reference with the variance ratio plot (Panel C) to distinguish a genuinely
flat-error model from one that is regressing to the mean.

### Panel C — Predicted vs Actual Variance Ratio per Horizon
The ratio `Var(predicted) / Var(actual)` computed at each of the 168 forecast steps.
The dashed black line at 1.0 is the ideal. Blue shading = under-dispersed region;
red shading = over-dispersed region.

**How to interpret:**

| Pattern | Meaning |
|---|---|
| Orange line stays near 1.0 across all horizons | Model maintains realistic spread at all forecast distances — genuine skill |
| Line drops below 1.0 after a few hours and keeps falling | Mean regression: model is predicting near-average values at longer horizons — predictions look plausible but miss peaks and troughs |
| Line starts above 1.0 (red zone) at horizon 1–5 | Decoder is over-dispersed initially — common in under-trained models |
| Line is flat below 1.0 for the entire range | Model systematically under-represents variation at all horizons |
| Line oscillates around 1.0 | Variance tracking is noisy but unbiased on average |

**Example — well-trained model:** Orange line hovers between 0.95–1.05 across all horizons.

**Example — mean-regressing model:** Line starts near 1.0 then steadily falls to ~0.7–0.8
by horizon 168. The model needs an attention mechanism or more training data.

**Example — under-trained model:** Line spikes above 1.0 at horizons 1–5, then drops
sharply below 1.0 and stays there. Both effects shrink after sufficient training.

---

## Per-Horizon Metrics vs Persistence Baseline

![Per-Horizon Metrics](per_horizon_metrics.png)

### What it shows
Five vertically stacked subplots sharing the same x-axis (forecast horizon 1–168h).
Each shows the LSTM metric (coloured line) and the **persistence baseline** (gray dashed
line). Vertical gray dashed lines mark day boundaries (1d–7d).

The persistence baseline naively repeats the last known abvaerk value for all 168 steps.
It is a strong baseline at short horizons but degrades quickly beyond 24h.

### Metrics explained

| Metric | Unit | Ideal direction | Formula |
|---|---|---|---|
| MSE | MWh² | Lower is better | mean((pred − actual)²) |
| RMSE | MWh | Lower is better | sqrt(MSE) — same unit as abvaerk |
| MAE | MWh | Lower is better | mean(\\|pred − actual\\|) |
| MAPE | % | Lower is better | mean(\\|pred − actual\\| / actual) × 100 |
| R² | dimensionless | Higher is better (max 1.0) | 1 - SS\\_res / SS\\_tot |

The dotted black line on the R² panel marks R² = 0 — below this the model is worse than
always predicting the mean.

### How to interpret each pattern

**MSE / RMSE / MAE:**

| Pattern | Meaning |
|---|---|
| LSTM line clearly below baseline at all horizons | Strong model — outperforms persistence at every step |
| LSTM below baseline at short horizons, above at long | Model has skill in the near term but loses it at multi-day distances |
| LSTM above baseline everywhere | Model is worse than naive persistence — undertrained or structural issue |
| Both lines flat (no growth with horizon) | Unusual; may indicate mean regression in both model and baseline |
| Both lines rise steeply after 24h | Normal degradation pattern for complex multi-day forecasts |

**MAPE:**
MAPE is sensitive to near-zero actual values. Spikes in the MAPE panel that don't
appear in MAE may indicate timesteps where actual abvaerk was very low (e.g. overnight
in summer).

**R²:**

| Pattern | Meaning |
|---|---|
| LSTM R² above baseline R² at all horizons | LSTM explains more variance than naive persistence everywhere ✓ |
| LSTM R² above 0 but below baseline | Model adds some signal but less than persistence — borderline useful |
| LSTM R² drops below 0 at long horizons | Model is worse than predicting the mean at those distances |
| Both LSTM and baseline R² near 0 at all horizons | High-variance demand — both models struggle to explain it |
| R² stays flat across all horizons | Model maintains skill across the full 7-day window |

---

## General notes

- All metrics are computed on the **test set only** ({test_size} samples, {test_pct:.1f}%
  of the data — chronologically the most recent). The model never saw this data during training.
- The persistence baseline uses the **last observed abvaerk value** from the encoder
  window repeated for all 168 forecast steps.
- A model trained for only **1–2 epochs** will typically show: high error, variance ratio
  well below 1.0 at long horizons, R² near or below the persistence baseline, and forecast
  windows that look flat or mean-like. These are training artefacts — always re-evaluate
  after full training.
"""
    readme_path = os.path.join(plot_dir, "README_Evaluation.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)

# ============================================================
# Ensemble README
# ============================================================

def generate_ensemble_readme(plot_dir, ensemble_size, model_filename="unknown", generated_plots=None):
    """
    Write README_Ensemble.md to plot_dir after all ensemble plots are saved.
    Active plots (in generated_plots) get an embedded image + full explanation.
    Disabled plots are listed briefly in an 'Optional plots' section.

    Args:
        plot_dir        : Directory where the README and plots are saved.
        ensemble_size   : Number of models in the ensemble.
        model_filename  : The base LSTM checkpoint the ensemble was built on.
        generated_plots : List of filenames actually saved this run.
    """
    if generated_plots is None:
        generated_plots = []

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Per-plot metadata: filename → (short title, explanation block)
    PLOT_DOCS = {
        f"week_forecast_ensemble_week2.png": (
            "Weekly Forecast with Uncertainty",
            f"""\
A single 168-hour (7-day) window from the test set. Three elements are plotted:
- **Actual abvaerk** (solid line) — the ground truth
- **Predicted mean** (solid line) — the ensemble average across all {ensemble_size} models
- **±2σ band** (shaded) — the total uncertainty interval covering ~95% of a Gaussian

| Pattern | Meaning |
|---|---|
| Actual stays inside the ±2σ band most of the time | Well-calibrated uncertainty — the model knows what it doesn't know |
| Actual frequently outside the band | Under-confident predictions — uncertainty is underestimated |
| Band is very wide throughout | Over-confident uncertainty estimate, or high inherent data noise |
| Band narrows at predictable hours and widens at transitions | Model is more certain at regular demand patterns — expected and healthy |
| Band widens beyond 24h and keeps growing | Normal: uncertainty accumulates with forecast distance |
| Band stays the same width regardless of horizon | Model may be collapsing to mean predictions at long horizons |
| Mean tracks actual well but band is very wide | Aleatoric uncertainty dominates — inherent noise in the demand signal |
| Mean drifts away from actual and band does not cover it | Systematic bias — model is missing a feature or pattern |"""
        ),
        "calibration_curve.png": (
            "Calibration Curve",
            """\
The x-axis shows the **theoretical coverage** of a Gaussian interval (e.g. 68% for ±1σ,
95% for ±2σ). The y-axis shows the **empirical coverage** — the actual fraction of test
points that fell inside that interval. The dashed diagonal is the ideal: perfect
calibration. Each point corresponds to a different σ multiplier (0.5σ → 3.0σ).

| Pattern | Meaning |
|---|---|
| Curve follows the diagonal closely | Well-calibrated — stated confidence matches actual coverage ✓ |
| Curve is above the diagonal | **Conservative** (over-dispersed) — intervals are too wide |
| Curve is below the diagonal | **Overconfident** (under-dispersed) — intervals are too narrow |
| Curve starts below diagonal then crosses above | Mixed calibration — over-dispersed only at high confidence levels |
| Curve is flat / horizontal | Pathological — uncertainty estimates are not varying meaningfully |
| S-shaped curve | Bimodal error distribution — model behaves differently in two regimes |

**Example — well-calibrated:** Points fall close to the diagonal. The 95% interval contains ~95% of the data.
**Example — overconfident:** Points cluster below the diagonal. The stated 95% interval only contains ~70% of the data.
**Example — under-trained ensemble:** Points cluster above the diagonal — models disagree too much."""
        ),
        "residuals_ensemble.png": (
            "Residuals Over Time",
            """\
The difference (actual − predicted mean) plotted for every test timestep in
chronological order. A rolling mean is overlaid to expose seasonal trends.

| Pattern | Meaning |
|---|---|
| Residuals centred near zero throughout | No systematic bias — model is well-calibrated on average |
| Persistent positive residuals | Model consistently under-predicts — consider adding features |
| Residuals spike at certain dates | Model failed on an unusual event (cold snap, holiday) |
| Residuals grow larger in winter | Model struggles with heating-season demand peaks |
| Residuals decrease over time | Distribution shift — later data is easier or model improves |"""
        ),
        "uncertainty_histogram.png": (
            "Uncertainty Distribution",
            """\
Histogram of total predictive standard deviation (σ) across all test timesteps.

| Pattern | Meaning |
|---|---|
| Narrow, single-peaked histogram | Model has similar confidence everywhere |
| Wide or flat histogram | Uncertainty varies greatly — expected for seasonal demand |
| Bimodal histogram | Two distinct uncertainty regimes (e.g. summer vs winter) |
| Histogram skewed right (long tail) | Occasional high-uncertainty predictions — check which timesteps |
| Very low std values throughout | Model may be under-dispersed — check calibration curve |"""
        ),
        "prediction_vs_actual.png": (
            "Predicted vs Actual Scatter",
            """\
Scatter plot of predicted mean (y) vs actual abvaerk (x) for every test timestep.
The dashed diagonal is perfect prediction (y = x).

| Pattern | Meaning |
|---|---|
| Points tightly clustered on the diagonal | High accuracy across the full range |
| Fan shape (wider at high values) | Heteroscedastic error — model struggles at peak demand |
| Points systematically above the diagonal | Model over-predicts on average |
| Points systematically below the diagonal | Model under-predicts on average |
| Two distinct clusters | Bi-modal demand — consider separate models for heating/non-heating seasons |"""
        ),
        "uncertainty_vs_error.png": (
            "Uncertainty vs Absolute Error",
            """\
Scatter of predicted total σ (x) vs absolute error (y) for every test timestep.
A well-calibrated model should show a positive correlation — higher stated uncertainty
should correspond to higher actual errors.

| Pattern | Meaning |
|---|---|
| Clear positive correlation | Uncertainty estimates are informative and trustworthy ✓ |
| Flat cloud (no correlation) | Uncertainty estimates are uninformative |
| Negative correlation | Pathological — model is most uncertain where it is most accurate |
| Points form two clusters | Two uncertainty regimes with different error characteristics |"""
        ),
    }

    # Split into active (generated this run) and disabled
    active   = [f for f in PLOT_DOCS if f in generated_plots]
    disabled = [f for f in PLOT_DOCS if f not in generated_plots]

    # Overview table rows (active plots only)
    overview_rows = ""
    for fname in active:
        title, _ = PLOT_DOCS[fname]
        overview_rows += f"| `{fname}` | {title} |\n"

    # Full section per active plot (image embedded + explanation)
    active_sections = ""
    for fname in active:
        title, explanation = PLOT_DOCS[fname]
        active_sections += f"""\
---

## `{fname}` — {title}

![{title}]({fname})

{explanation}

"""

    # Brief section for disabled plots
    if disabled:
        disabled_section = "---\n\n## Optional Plots (currently disabled)\n\n"
        disabled_section += (
            "Enable these in `EnsembleOutput.py` by uncommenting the relevant lines "
            "in `_GeneratePlots`.\n\n"
        )
        for fname in disabled:
            title, explanation = PLOT_DOCS[fname]
            disabled_section += f"### `{fname}` — {title}\n\n{explanation}\n\n"
    else:
        disabled_section = ""

    content = f"""\
# Ensemble LSTM — Uncertainty Quantification Plots

Auto-generated by `EnsembleOutput.py` on {generated_at}.

---

## What is the Ensemble?

Instead of training a single LSTM model, the ensemble trains **{ensemble_size} independent
models** with different random seeds. Each model sees the same data but starts from a
different random initialisation, producing slightly different predictions.

The spread across these predictions tells us how **uncertain** the model is:

| Uncertainty type | Source | Meaning |
|---|---|---|
| **Epistemic** | Disagreement between the {ensemble_size} models | What the model *doesn't know* — reduces with more data/training |
| **Aleatoric** | Each model's own predicted variance (GaussianNLL output) | Inherent noise in the data — cannot be reduced |
| **Total** | Combined epistemic + aleatoric | The full predictive uncertainty |

Base model: `{model_filename}`

---

## Plots Overview

| File | Contents |
|---|---|
{overview_rows}
{active_sections}{disabled_section}---

## General Notes

- All plots use the **test set only** — the ensemble never saw this data during training.
- The ensemble was trained with **GaussianNLLLoss**, so each model outputs both a
  predicted mean and a predicted variance. Aleatoric uncertainty comes from the variance
  output; epistemic uncertainty comes from disagreement between the {ensemble_size} models.
- A larger ensemble (more models) reduces the variance of the epistemic uncertainty
  estimate but increases training time proportionally.
"""
    readme_path = os.path.join(plot_dir, "README_Ensemble.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)


    content = f"""\
# Ensemble LSTM — Uncertainty Quantification Plots

Auto-generated by `EnsembleOutput.py`.

---

## What is the Ensemble?

Instead of training a single LSTM model, the ensemble trains **{ensemble_size} independent
models** with different random seeds. Each model sees the same data but starts from a
different random initialisation, producing slightly different predictions.

The spread across these predictions tells us how **uncertain** the model is:

| Uncertainty type | Source | Meaning |
|---|---|---|
| **Epistemic** | Disagreement between the {ensemble_size} models | What the model *doesn't know* — reduces with more data/training |
| **Aleatoric** | Each model's own predicted variance (GaussianNLL output) | Inherent noise in the data — cannot be reduced |
| **Total** | Combined epistemic + aleatoric | The full predictive uncertainty |

Base model: `{model_filename}`

---

## Plots Overview

| File | Contents |
|---|---|
| `week_forecast_ensemble_week2.png` | One-week forecast with ±2σ uncertainty band |
| `calibration_curve.png` | Empirical vs theoretical coverage of prediction intervals |

The following plots are available but currently disabled — enable them in `EnsembleOutput.py`:

| File | Contents |
|---|---|
| `residuals_ensemble.png` | Ensemble residuals (actual − predicted mean) over time |
| `uncertainty_histogram.png` | Distribution of total predictive uncertainty (std) |
| `prediction_vs_actual.png` | Scatter of predicted mean vs actual abvaerk |
| `uncertainty_vs_error.png` | Scatter of predicted uncertainty vs absolute error |

---

## Weekly Forecast with Uncertainty

![Weekly Forecast with Uncertainty](week_forecast_ensemble_week2.png)

### What it shows
A single 168-hour (7-day) window from the test set. Three elements are plotted:
- **Actual abvaerk** (solid line) — the ground truth
- **Predicted mean** (solid line) — the ensemble average across all {ensemble_size} models
- **±2σ band** (shaded) — the total uncertainty interval covering ~95% of a Gaussian

### How to interpret

| Pattern | Meaning |
|---|---|
| Actual stays inside the ±2σ band most of the time | Well-calibrated uncertainty — the model knows what it doesn't know |
| Actual frequently outside the band | Under-confident predictions — uncertainty is underestimated |
| Band is very wide throughout | Over-confident uncertainty estimate, or high inherent data noise |
| Band narrows at predictable hours (e.g. midday) and widens at transitions | Model is more certain at regular demand patterns — expected and healthy |
| Band widens beyond 24h and keeps growing | Normal: uncertainty accumulates with forecast distance |
| Band stays the same width regardless of horizon | Model may be collapsing to mean predictions at long horizons |
| Mean tracks actual well but band is very wide | Aleatoric uncertainty dominates — inherent noise in the demand signal |
| Mean drifts away from actual and band does not cover it | Systematic bias — model is missing a feature or pattern |

---

## Calibration Curve

![Calibration Curve](calibration_curve.png)

### What it shows
The x-axis shows the **theoretical coverage** of a Gaussian interval (e.g. 68% for ±1σ,
95% for ±2σ). The y-axis shows the **empirical coverage** — the actual fraction of test
points that fell inside that interval. The dashed diagonal is the ideal: perfect
calibration.

Each point on the curve corresponds to a different σ multiplier (from 0.5σ to 3.0σ).

### How to interpret

| Pattern | Meaning |
|---|---|
| Curve follows the diagonal closely | Well-calibrated — stated confidence matches actual coverage ✓ |
| Curve is above the diagonal | **Conservative** (over-dispersed) — intervals are too wide; the model is more uncertain than it needs to be |
| Curve is below the diagonal | **Overconfident** (under-dispersed) — intervals are too narrow; the model underestimates uncertainty |
| Curve starts below diagonal then crosses above | Mixed calibration — well-calibrated at low confidence, over-dispersed at high confidence |
| Curve is flat / horizontal | Pathological — uncertainty estimates are not varying meaningfully |
| S-shaped curve | Bimodal error distribution — model behaves differently in two regimes (e.g. heating season vs summer) |

**Example — well-calibrated:** Points fall close to the diagonal across the full range.
The 95% interval actually contains ~95% of the data.

**Example — overconfident:** Points cluster below the diagonal. The stated 95% interval
only contains ~70% of the data — the model is too sure of itself.

**Example — under-trained ensemble:** Points cluster above the diagonal. The models
disagree too much (high epistemic uncertainty), making intervals unnecessarily wide.

---

## Optional Plots (currently disabled)

### Residuals Over Time
The difference (actual − predicted mean) plotted for every test timestep. Useful for
detecting systematic bias over time or at certain periods (e.g. winter peaks).

### Uncertainty Distribution
Histogram of total predictive std across all test timesteps. A narrow, peaked histogram
means the model has similar confidence everywhere. A wide or multi-modal histogram means
uncertainty varies significantly (e.g. higher in winter, lower in summer).

### Predicted vs Actual Scatter
Each point is one timestep. Points on the diagonal = perfect prediction. Fan shape =
heteroscedastic error (larger errors at high demand values).

### Uncertainty vs Error
Scatter of predicted std (x) vs absolute error (y). If the model is well-calibrated,
there should be a positive correlation — higher stated uncertainty should correspond to
higher actual errors. A flat cloud means uncertainty estimates are uninformative.

---

## General Notes

- All plots use the **test set only** — the ensemble never saw this data during training.
- The ensemble was trained with **GaussianNLLLoss**, so each model outputs both a
  predicted mean and a predicted variance. Aleatoric uncertainty comes from the variance
  output; epistemic uncertainty comes from disagreement between the {ensemble_size} models.
- A larger ensemble (more models) reduces the variance of the epistemic uncertainty
  estimate but increases training time proportionally.
"""
    readme_path = os.path.join(plot_dir, "README_Ensemble.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)

